# Paste your MongoDB Connection String here
mongo_uri = "mongodb+srv://username:password@cluster0.mongodb.net/personal_book?retryWrites=true&w=majority"

# Paste your Random Secret here, this below generated by running "openssl rend -hex 32"
jwt_secret = "e6c55b2c19eadd30345f985cde2af973bd8c2f01f15061acdaab2c77577e3ff4"

# Paste your Slack Webhook URL here
sender_email_address = "shashank9928@gmail.com"
